import React, { useEffect, useState } from 'react'
import type { Profile, Trip } from '../domain'
import countries from '../data/countries.json'
import { addTripMemory, addTripPlace, deleteMemoryPhoto, deleteTripMemory, deleteTripPhoto, deleteTripPlace, geocodePlace, loadTripContent, updateTripPlaceCoordinates, uploadMemoryPhoto, uploadTripPhoto, type TripMemory, type TripPhoto, type TripPlace } from '../lib/TripContentRuntime'
import GooglePhotosPickerButton from './GooglePhotosPickerButton'

const countryNames = new Map((countries as {id:string;name:string}[]).map((c)=>[c.id,c.name]))

function readFile(file:File):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}

export default function TripContentPanel({atlasId,trip,profiles,focusPlaceId}:{atlasId:string;trip:Trip;profiles:Profile[];focusPlaceId?:string|null}){
  const [places,setPlaces]=useState<TripPlace[]>([]); const [memories,setMemories]=useState<TripMemory[]>([]); const [photos,setPhotos]=useState<TripPhoto[]>([])
  const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [locatingId,setLocatingId]=useState<string|null>(null)
  const [placeName,setPlaceName]=useState(''); const [placeCategory,setPlaceCategory]=useState(''); const [placeCountry,setPlaceCountry]=useState(trip.countryIds[0]||''); const [placeNote,setPlaceNote]=useState('')
  const [memoryTitle,setMemoryTitle]=useState(''); const [memoryBody,setMemoryBody]=useState(''); const [memoryPlace,setMemoryPlace]=useState(''); const [memoryPerson,setMemoryPerson]=useState(''); const [memoryDate,setMemoryDate]=useState(''); const [memoryFile,setMemoryFile]=useState<File|null>(null)
  async function refresh(){setError(null);try{const content=await loadTripContent(trip.id);setPlaces(content.places);setMemories(content.memories);setPhotos(content.photos)}catch(e){setError(e instanceof Error?e.message:'Trip content could not be loaded.')}}
  useEffect(()=>{void refresh()},[trip.id])
  useEffect(()=>{if(!focusPlaceId)return;const timer=window.setTimeout(()=>document.getElementById(`trip-place-${focusPlaceId}`)?.scrollIntoView({behavior:'smooth',block:'center'}),150);return()=>window.clearTimeout(timer)},[focusPlaceId,places.length])
  async function addPlace(e:React.FormEvent){e.preventDefault();setBusy(true);setError(null);try{let coords:Awaited<ReturnType<typeof geocodePlace>>=null;try{coords=await geocodePlace(placeName,countryNames.get(placeCountry))}catch{/* Place is still valid if external map lookup is unavailable. */}await addTripPlace({tripId:trip.id,name:placeName,category:placeCategory||undefined,countryId:placeCountry||undefined,note:placeNote||undefined,latitude:coords?.latitude,longitude:coords?.longitude});setPlaceName('');setPlaceCategory('');setPlaceNote('');await refresh()}catch(e){setError(e instanceof Error?e.message:'Place could not be added.')}finally{setBusy(false)}}
  async function locatePlace(place:TripPlace){setLocatingId(place.id);setError(null);try{const result=await geocodePlace(place.name,countryNames.get(place.countryId||''));if(!result)throw new Error(`We could not find ${place.name} on the map. Try making the place name more specific.`);await updateTripPlaceCoordinates(place.id,result.latitude,result.longitude);await refresh()}catch(e){setError(e instanceof Error?e.message:'Place could not be located.')}finally{setLocatingId(null)}}
  async function addMemory(e:React.FormEvent){e.preventDefault();setBusy(true);try{const id=await addTripMemory({tripId:trip.id,title:memoryTitle,body:memoryBody||undefined,placeId:memoryPlace||undefined,personId:memoryPerson||undefined,memoryDate:memoryDate||undefined});if(memoryFile)await uploadMemoryPhoto({atlasId,tripId:trip.id,memoryId:id,dataUrl:await readFile(memoryFile)});setMemoryTitle('');setMemoryBody('');setMemoryPlace('');setMemoryPerson('');setMemoryDate('');setMemoryFile(null);await refresh()}catch(e){setError(e instanceof Error?e.message:'Memory could not be added.')}finally{setBusy(false)}}
  async function addPhoto(file?:File){if(!file)return;setBusy(true);try{await uploadTripPhoto({atlasId,tripId:trip.id,dataUrl:await readFile(file)});await refresh()}catch(e){setError(e instanceof Error?e.message:'Photo could not be uploaded.')}finally{setBusy(false)}}
  async function addGooglePhotos(selected:{dataUrl:string;filename?:string}[]){setBusy(true);setError(null);try{for(const photo of selected){await uploadTripPhoto({atlasId,tripId:trip.id,dataUrl:photo.dataUrl,caption:undefined})}await refresh()}catch(e){setError(e instanceof Error?e.message:'Selected Google Photos could not be imported.');throw e}finally{setBusy(false)}}
  async function removePhoto(photo:TripPhoto){if(!window.confirm('Remove this photo from the trip?'))return;setBusy(true);try{await deleteTripPhoto(photo);await refresh()}catch(e){setError(e instanceof Error?e.message:'Photo could not be removed.')}finally{setBusy(false)}}
  async function removePlace(place:TripPlace){if(!window.confirm(`Remove ${place.name} from this trip? Memories linked to it will remain, but no longer be linked to the place.`))return;setBusy(true);try{await deleteTripPlace(place.id);await refresh()}catch(e){setError(e instanceof Error?e.message:'Place could not be removed.')}finally{setBusy(false)}}
  async function removeMemory(memory:TripMemory){if(!window.confirm(`Delete the memory “${memory.title}”?`))return;setBusy(true);try{await deleteTripMemory(memory);await refresh()}catch(e){setError(e instanceof Error?e.message:'Memory could not be removed.')}finally{setBusy(false)}}
  async function removeMemoryPhoto(memory:TripMemory){if(!window.confirm('Remove this photo from the memory?'))return;setBusy(true);try{await deleteMemoryPhoto(memory);await refresh()}catch(e){setError(e instanceof Error?e.message:'Memory photo could not be removed.')}finally{setBusy(false)}}
  return <section className="trip-next-section">
    <h2>Places & memories</h2>
    {error&&<p className="auth-error" role="alert">{error}</p>}
    <div className="trip-content-grid">
      <div><h3>Trip photos</h3><div className="trip-media-actions"><label className="secondary-btn">+ Upload from device<input hidden type="file" accept="image/*" multiple onChange={(e)=>{const files=Array.from(e.target.files||[]);void (async()=>{for(const file of files)await addPhoto(file)})()}}/></label><GooglePhotosPickerButton disabled={busy} onPicked={addGooglePhotos}/></div><div className="trip-photo-grid">{photos.map(p=><figure key={p.id}>{p.signedUrl&&<img src={p.signedUrl} alt={p.caption||'Trip photo'}/>} {p.caption&&<figcaption>{p.caption}</figcaption>}<button className="danger-link" type="button" disabled={busy} onClick={()=>void removePhoto(p)}>Remove photo</button></figure>)}</div></div>
      <div><h3>Places</h3><p className="trip-form-help">Places are automatically located on the map when possible. They will then appear as dots on each traveller’s personal map.</p><form onSubmit={addPlace} className="trip-form compact"><label>Place name<input required value={placeName} onChange={e=>setPlaceName(e.target.value)} placeholder="e.g. Nice, Paris, Promenade des Anglais"/></label><label>Type<input value={placeCategory} onChange={e=>setPlaceCategory(e.target.value)} placeholder="City, beach, hotel, restaurant..."/></label><label>Country<select value={placeCountry} onChange={e=>setPlaceCountry(e.target.value)}><option value="">Not specified</option>{trip.countryIds.map(id=><option key={id} value={id}>{countryNames.get(id)||id}</option>)}</select></label><label>Note<textarea rows={2} value={placeNote} onChange={e=>setPlaceNote(e.target.value)}/></label><button className="secondary-btn" disabled={busy}>Add place</button></form>{places.map(p=><article id={`trip-place-${p.id}`} className={`trip-detail-section${focusPlaceId===p.id?' focused-place':''}`} key={p.id}><strong>{p.name}</strong>{p.category&&<span> · {p.category}</span>}{p.countryId&&<div>{countryNames.get(p.countryId)||p.countryId}</div>}{p.note&&<p>{p.note}</p>}<div className="inline-actions">{typeof p.latitude==='number'&&typeof p.longitude==='number'?<small>● Shown on traveller maps</small>:<button className="secondary-btn" type="button" disabled={locatingId===p.id} onClick={()=>void locatePlace(p)}>{locatingId===p.id?'Finding…':'Find on map'}</button>}<button className="danger-link" type="button" disabled={busy} onClick={()=>void removePlace(p)}>Remove place</button></div></article>)}</div>
      <div><h3>Memories</h3><form onSubmit={addMemory} className="trip-form compact"><label>Memory title<input required value={memoryTitle} onChange={e=>setMemoryTitle(e.target.value)} placeholder="e.g. Dylan learned to snorkel"/></label><label>Memory<textarea rows={3} value={memoryBody} onChange={e=>setMemoryBody(e.target.value)}/></label><label>Place<select value={memoryPlace} onChange={e=>setMemoryPlace(e.target.value)}><option value="">No specific place</option>{places.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Whose memory?<select value={memoryPerson} onChange={e=>setMemoryPerson(e.target.value)}><option value="">Shared / not specified</option>{profiles.filter(p=>p.personId&&trip.participantIds.includes(p.personId)).map(p=><option key={p.id} value={p.personId}>{p.name}</option>)}</select></label><label>Date<input type="date" value={memoryDate} onChange={e=>setMemoryDate(e.target.value)}/></label><label>Photo<input type="file" accept="image/*" onChange={e=>setMemoryFile(e.target.files?.[0]||null)}/></label><button className="secondary-btn" disabled={busy}>Add memory</button></form>{memories.map(m=><article className="trip-detail-section" key={m.id}>{m.photoUrl&&<><img className="trip-memory-photo" src={m.photoUrl} alt={m.title}/><button className="danger-link" type="button" disabled={busy} onClick={()=>void removeMemoryPhoto(m)}>Remove photo</button></>}<strong>{m.title}</strong>{m.memoryDate&&<div>{m.memoryDate}</div>}{m.body&&<p>{m.body}</p>}<button className="danger-link" type="button" disabled={busy} onClick={()=>void removeMemory(m)}>Delete memory</button></article>)}</div>
    </div>
  </section>
}
